#Here locators for assignments page are present

AssignmentsHeadingLocator = "//*[@id='title']"
AssignmentsAllButtonLocator = "//*[@id='filter']/div/span"
AssignmentsCreateNewButtonLocator = "//*[contains(text(),'Create new')]"
AssignmentsDescriptionColumnHeadingLocator = "//*[@id='wrapper']/app-assignments-table/div/table/tr[1]/th[2]"
AssignmentsTypeColumnHeadingLocator = "//*[@id='wrapper']/app-assignments-table/div/table/tr[1]/th[3]"
AssignmentsSentColumnHeadingLocator = "//*[@id='wrapper']/app-assignments-table/div/table/tr[1]/th[4]"
AssignmentsSentToColumnHeadingLocator = "//*[@id='wrapper']/app-assignments-table/div/table/tr[1]/th[5]"
AssignmentsOpenedColumnHeadingLocator = "//*[@id='wrapper']/app-assignments-table/div/table/tr[1]/th[6]"
AssignmentsCreateNewSendSongButtonLocator = "//*[contains(text(),'Send a song')]"
AssignmentsCreateNewSendWordButtonLocator = "//*[contains(text(),'Send a word')]"
AssignmentsCreateNewSendSongTrackFieldLocator = "//*[contains(text(),'Track')]/../../../input"
AssignmentsCreateNewSendSongGroupFieldLocator = "//*[contains(text(),'Group')]/../../../mat-select"
AssignmentsCreateNewSendSongGroupFieldTestingElementLocator = "//*[contains(text(),'Testing')]"
AssignmentsCreateNewSendSongNotesFieldLocator = "//*[contains(text(),'Notes (Optional)')]"
AssignmentsCreateNewSendSongNextButtonLocator = "//*[contains(text(),'Next')]"
AssignmentsCreateNewSendSongSelectLyricsLocator = "//*[contains(text(),'Select lyrics')]"
AssignmentsCreateNewSendSongSubmitButtonLocator = "//*[contains(text(),'Submit')]"
AssignmentsCreateNewSendSongReviewWorkHeadingLocator = "//*[contains(text(),'Review your work')]"
AssignmentsCreateNewSendSongCancelButtonLocator = "//*[contains(text(),'Cancel')]"
AssignmentsCreateNewSendSongSendButtonLocator = "//*[@id='actions']/button[1]"
AssignmentsCreateNewSendSongSuccessMessageLocator = "//*[contains(text(),'Song sent successfully')]"
AssignmentsCreateNewSendWordHeadingLocator = "//*[contains(text(),'Send words')]"
AssignmentsCreateNewSendWordYourWordsFieldLocator = "//*[contains(text(),'Your words')]/../../../mat-chip-list//input"
AssignmentsCreateNewSendWordGroupFieldLocator = "//*[contains(text(),'Group')]/../../../mat-select"
AssignmentsCreateNewSendWordGroupFieldTestingElementLocator = "(//*[contains(text(),'Testing')])[last()]"
AssignmentsCreateNewSendWordNotesFieldLocator = "//*[contains(text(),'Notes (Optional)')]"
AssignmentsCreateNewSendWordSendButtonLocator = "//app-send-word/form/button"
AssignmentsCreateNewSendWordSuccessMessageLocator = "//*[contains(text(),'Your words were sent successfully')]"

