# Here all the locators of Classes page are present

ClassesCloseButtonLocator = "//*[contains(text(), 'Close')]"
ClassesHeadingTextLocator = "//*[@id='wrapper']/div[1]/h1"
ClassesSideMenuAllButtonLocator = "//*[@id='menu-col']/li[1]/p"
ClassesAllClassesTableHeadingLocator = "//*[@id='content']/div/div[1]/h2"
ClassesPlusButtonLocator = "//*[@id='actions']/i[1]"
ClassPlusButtonPopupLocator = "wrapper"
ClassesEyeButtonLocator = "//*[@id='actions']/i[2]"
ClassesShowMeHowLocator = "//*[@id='info']"
ClassesShowMeHowPopupHeadingLocator = "//*[@id='wrapper']/h2"
ClassesShowMeHowPopupSubHeadingFirstLocator = "//*[@id='wrapper']/h3[1]"
ClassesShowMeHowPopupSubHeadingSecondLocator = "//*[@id='wrapper']/h3[2]"
ClassesShowMeHowPopupCloseButtonLocator = "//*[@id='wrapper']/button"
ClassesAllClassesTableHashColumnLocator = "//*[@id='content']/table/tr[1]/th[1]"
ClassesAllClassesTableNameColumnLocator = "//*[@id='content']/table/tr[1]/th[2]"
ClassesAllClassesTableStudentsColumnLocator = "//*[@id='content']/table/tr[1]/th[3]"
ClassesAllClassesTableWordsSentColumnLocator = "//*[@id='content']/table/tr[1]/th[4]"
ClassesAllClassesTableSongHearedColumnLocator = "//*[@id='content']/table/tr[1]/th[5]"
ClassesAllClassesTableQuizzesAnsweredColumnLocator = "//*[@id='content']/table/tr[1]/th[6]"
ClassesAllClassesTableThreeDotsColumnLocator = "//*[@id='content']/table/tr[2]/td[7]/i"
ClassPlusButtonCreateNewGroupHeadingLocator = "//*[@id='wrapper']/h3"
ClassPlusButtonCreateNewGroupFieldLocator = "//*[contains(text(),'Group name')]"
ClassPlusButtonCreateNewClassFieldLocator = "(//*[contains(text(),'Class')])[2]"
ClassPlusButtonCreateNewGrammarLevelFieldLocator = "//*[contains(text(),'Default grammar level')]"
ClassPlusButtonCreateNewDefaultLanguageFieldLocator = "//*[contains(text(),'Hebrew')]"
ClassPlusButtonCreateNewParentContainerFieldLocator = "//*[contains(text(),'Parent container')]"
ClassPlusButtonCreateNewIDMOrganizationIDFieldLocator = "//*[contains(text(),'IDM organization id')]"
ClassPlusButtonCreateNewAllowedUsersCountFieldLocator = "//*[contains(text(),'Allowed users count')]"
ClassPlusButtonCreateNewExpirationFieldLocator = "//*[contains(text(),'Expiration date')]"
ClassPlusButtonCreateNewSaveButtonLocator = "(//*[contains(text(),'Create')])[2]"
ClassPlusButtonCreateNewErrorMessageLocator = "//*[@id='wrapper']/form/p"
ClassEyeButtonPopupHeadingLocator = "//*[text()='Select classes']"
ClassEyeButtonPopupTableFirstColumnLocator = "//*[@id='table-wrapper']/table/tr[1]/th[1]"
ClassEyeButtonPopupTableSecondColumnLocator = "(//*[text()='Name'])[2]"
ClassEyeButtonPopupTableThirdColumnLocator = "(//*[text()='Students'])[2]"
ClassEyeButtonPopupSaveButtonLocator = "//*[text()='Save']"
ClassEyeButtonPopupSuccessMessageLocator = "//*[text()='Changes saved successfully']"
ClassThreeDotsPopupWatchClassProgressLocator = "//*[text()='watch class progress']"
ClassThreeDotsPopupContentPolicyLocator = "//*[text()='Content policy']"
ClassThreeDotsPopupRemoveGroupLocator = "//*[text()='Remove group']"
ClassThreeDotsPopupEditClassLocator = "//*[text()='Edit class']"
ClassThreeDotsEditClassPopupHeadingLocator = "//*[@id='wrapper']/h3"
ClassThreeDotsEditClassPopupGroupNameFieldLocator = "//*[text()='Group name']"
ClassThreeDotsEditClassPopupGroupTypeFieldLocator = "//*[text()='Group type']"
ClassThreeDotsEditClassPopupDefaultGrammarLevelFieldLocator = "//*[text()='Default grammar level']"
ClassThreeDotsEditClassPopupDefaultLanguageFieldLocator = "//*[text()='Default language']"
ClassThreeDotsEditClassPopupParentContainerFieldLocator = "//*[text()='Parent container']"
ClassThreeDotsEditClassPopupIDMOrganizationIDFieldLocator = "//*[text()='IDM organization id']"
ClassThreeDotsEditClassPopupAllowedUsersCountFieldLocator = "//*[text()='Allowed users count']"
ClassThreeDotsEditClassPopupExpirationDateFieldLocator = "//*[text()='Expiration date']"
ClassThreeDotsEditClassPopupUpdateButtonLocator = "//*[@id='wrapper']/form/button"
ClassThreeDotsEditClassPopupUpdatedSuccessMessageLocator = "//*[text()='Group updated successfully.']"
ClassThreeDotsWatchClassProgressHeadingLocator = "//*[@id='header']/div/h1"
ClassThreeDotsWatchClassProgressTimelineTextLocator = "//*[contains(text(),'Timeline')]"
ClassThreeDotsWatchClassProgressGradesDistributionTextLocator = "//*[@id='grades-distribution-header']"
ClassThreeDotsWatchClassProgressAllLessonsTextLocator = "//*[contains(text(),'All Lessons')]"
ClassThreeDotsWatchClassProgressAssignmentsCompletedTextLocator = "//*[contains(text(),'Assignments completed')]"
ClassThreeDotsWatchClassProgressMostSelectedWordsTextLocator = "//*[contains(text(),'Most Selected Words')]"
ClassThreeDotsWatchClassProgressCloseButtonLocator = "//*[text()='Close']"
ClassThreeDotsPopupContentPolicyPopupHeadingLocator = "//*[@id='wrapper']/h3"
ClassThreeDotsPopupContentPolicyPopupAbuseAndViolenceBarHeadingTextLocator = "//*[text()='Abuse and Violence']"
ClassThreeDotsPopupContentPolicyPopupCoarseLanguageBarHeadingTextLocator = "//*[text()='Coarse Language']"
ClassThreeDotsPopupContentPolicyPopupGamblingBarHeadingTextLocator = "//*[text()='Gambling']"
ClassThreeDotsPopupContentPolicyPopupGenderIdentityAndSexualBarHeadingTextLocator = "//*[text()='Gender identity and Sexual" \
                                                                             " Orientation']"
ClassThreeDotsPopupContentPolicyPopupPoliticalBarHeadingTextLocator = "//*[text()='Political']"
ClassThreeDotsPopupContentPolicyPopupRaceAndEthnicityBarHeadingTextLocator = "//*[text()='Race and ethnicity']"
ClassThreeDotsPopupContentPolicyPopupReligionBarHeadingTextLocator = "//*[text()='Religion']"
ClassThreeDotsPopupContentPolicyPopupSexualBarHeadingTextLocator = "//*[text()='Sexual']"
ClassThreeDotsPopupContentPolicyPopupSubstanceUseBarHeadingTextLocator = "//*[text()='Substance Use']"
ClassThreeDotsPopupContentPolicyPopupCancelButtonLocator = "//*[text()='Cancel']"
ClassThreeDotsPopupContentPolicyPopupSaveButtonLocator = "//*[text()='Save']"
ClassThreeDotsPopupRemoveGroupHeadingLocator = "//*[text()='Are you sure you want to delete the group']"
ClassThreeDotsPopupRemoveGroupRemoveButtonLocator = "//*[text()='Remove']"
ClassThreeDotsPopupRemoveGroupCancelButtonLocator = "//*[text()='Cancel']"
ClassThreeDotsPopupRemoveGroupRemovedSuccessMessageLocator = "//*[contains(text(),'Group removed successfully')]"
