# Here locators of Dashboard page are present

DashboardHeadingLocator = "//*[@id='wrapper']/div[1]/h1"
DashboardStudentsLoggedInLocator = "//*[contains(text(), 'students currently logged in')]"
DashboardUsersActiveLocator = "//*[contains(text(), 'Users are active now')]"
DashboardActiveUsersGraphCardLocator = "//*[@id='main-card']"
DashboardVocabularyQuizzesElementLocator = "//*[text()='Vocabulary quizzes']"
DashboardGrammarQuizzesElementLocator = "//*[text()='Grammar quizzes']"
DashboardUnseenTestsElementLocator = "//*[text()='Unseen tests']"
DashboardSpeakingTestsLocator = "//*[text()='Speaking tests']"
DashboardFillBlanksTestsLocator = "//*[text()='Fill Blanks tests']"
DashboardWardPausesTestsLocator = "//*[text()='ward pauses tests']"
DashboardAssignmentsCardLocator = "//*[text()='Assignments']"
DashboardMostPressedWordsLocator = "//*[text()='Most pressed words']"
DashboardLogoutButtonLocator = "//*[contains(text(), 'Log out')]"
