# Here all the locators of Marketplace page are present

MarketplaceHeadingLocator = "(//*[text()='Marketplace'])[2]"
MarketplaceCreateALessonButtonLocator = "//*[contains(text(),'Create a lesson')]"
MarketplaceCreateALessonTitleFieldLocator = "//*[text()='Title']"
MarketplaceCreateALessonDescriptionFieldLocator = "//*[text()='Description']"
MarketplaceCreateALessonSearchSongFieldLocator = "//*[text()='Search song']"
MarketplaceCreateALessonDifficultyFieldLocator = "//*[text()='Difficulty']"
MarketplaceCreateALessonDurationFieldLocator = "//*[text()='Duration']"
MarketplaceCreateALessonAgeGradeFieldLocator = "//*[text()='Age grade']"
MarketplaceCreateALessonLearnedWordsFieldLocator = "//*[text()='Learned words']"
MarketplaceCreateALessonMakePublicFieldLocator = "//*[text()='Make public']"
MarketplaceCreateALessonSaveButtonLocator = "//*[contains(text(),'Save')]"
MarketplaceCreateALessonCreatedSuccessMessageLocator = "//*[contains(text(),'Lesson createed successfully.')]"
MarketplaceCreateALessonCreatedLessonHeadingLocator = "//*[@id='main-details']/h1"
MarketplaceCreateALessonCreatedLessonViewEditButtonLocator = "//*[contains(text(),'Edit')]"
MarketplaceCreateALessonCreatedLessonViewUseLessonButtonLocator = "//*[contains(text(),'Use lesson')]"
MarketplaceCreateALessonCreatedLessonViewUseLessonKeepButtonLocator = "//*[text()='Keep']"
MarketplaceCreateALessonCreatedLessonViewUseLessonEditButtonLocator = "//*[text()='Edit']"
MarketplaceCreateALessonCreatedLessonViewUseLessonGroupFieldLocator = "//*[text()='Group']"
MarketplaceCreateALessonCreatedLessonViewUseLessonSendButtonLocator = "//*[text()='Send']"
MarketplaceCreateALessonCreatedLessonViewUseLessonCancelButtonLocator = "//*[contains(text(),'Cancel')]"
MarketplaceCreateALessonCreatedLessonViewUseLessonEditPopupContinueButtonLocator = "//*[text()='Continue']"
MarketplaceCreateALessonCreatedLessonViewUseLessonEditPopupCancelButtonLocator = "//*[contains(text(),'Cancel')]"
MarketplaceCreateALessonCreatedLessonViewLikeButtonLocator = "//*[@id='main-details']/div[1]/button[2]"
MarketplaceCreateALessonCreatedLessonViewDislikeButtonLocator = "//*[@id='main-details']/div[1]/button[3]"
MarketplaceCreateALessonCreatedLessonViewEditLessonHeadingLocator = "//*[contains(text(),'Edit lesson')]"
MarketplaceCreateALessonCreatedLessonViewEditLessonTitleFieldLocator = "//*[text()='Title']/../../../input"
MarketplaceCreateALessonCreatedLessonViewEditLessonDescriptionFieldLocator = "//*[text()='Description']/../../.." \
                                                                             "/textarea"
MarketplaceCreateALessonCreatedLessonViewEditLessonSearchSongFieldLocator = "//*[text()='Search song']/../../../input"
MarketplaceCreateALessonCreatedLessonViewEditLessonDifficultyFieldLocator = "//*[text()='Difficulty']/../../.." \
                                                                            "/mat-select"
MarketplaceCreateALessonCreatedLessonViewEditLessonDurationFieldLocator = "//*[text()='Duration']/../../../mat-select"
MarketplaceCreateALessonCreatedLessonViewEditLessonAgeGradeFieldLocator = "//*[text()='Age grade']/../../../mat-select"
MarketplaceCreateALessonCreatedLessonViewEditLessonLearnedWordsFieldLocator = "//*[text()='Learned words']/../.."
MarketplaceCreateALessonCreatedLessonViewEditLessonMakePublicFieldLocator = "//*[text()='Make public']"
MarketplaceCreateALessonCreatedLessonViewEditLessonSaveButtonLocator = "//*[contains(text(),'Save')]"
MarketplaceCreateALessonCreatedLessonViewEditLessonUpdatedSuccessMessageLocator = "//*[contains(text(),'Lesson " \
                                                                                  "updated successfully.')]"
MarketplaceCreateALessonCreatedLessonViewEditedLessonViewDurationLocator = "//*[contains(text(),'Duration')]/" \
                                                                           "../*[contains(text(),'min')]"
MarketplaceCreateALessonCreatedLessonViewEditedLessonViewEditLessonAddAssignmentButtonLocator = "//*[contains(" \
                                                                                                "text(),'Add')]"
AddAssignmentPopupHeadingLocator = "//*[contains(text(),'Select the assignment type from the list below')]"
AddAssignmentPopupGrammarTestLocator = "//*[contains(text(),'Grammar test')]"
AddAssignmentPopupUnseenLocator = "//*[contains(text(),'Unseen')]"
AddAssignmentPopupFillBlanksLocator = "//*[contains(text(),'Fill blanks')]"
AddAssignmentPopupWordPauseLocator = "//*[contains(text(),'Word-pause')]"
AddAssignmentPopupVocabularyQuizLocator = "//*[contains(text(),'Vocabulary quiz')]"
AddAssignmentPopupSpeakingQuizLocator = "//*[contains(text(),'Speaking quiz')]"
AddAssignmentPopupNextButtonLocator = "//*[text()='Next']"
AddAssignmentPopupGrammarTestFirstPopupHeadingLocator = "//*[text()='Select the base text for the questions']"
AddAssignmentPopupGrammarTestSecondPopupHeadingLocator = "//*[contains(text(),'Select the questions" \
                                                        " you want to use or create your own')]"
AddAssignmentPopupGrammarTestThirdPopupHeadingLocator = "//*[text()='Review your work']"
AddAssignmentPopupSuccessfulCreation = "//*[contains(text(),'Created successfully')]"
AddAssignmentPopupUnseenFirstPopupHeadingLocator = "//*[text()='Select the base text for the questions']"
AddAssignmentPopupUnseenFirstPopupTextareaLocator = "//*[@id='scroll-wrapper']/form/textarea"
AddAssignmentPopupWordPauseFirstPopupTextareaLocator = "//*[text()='Select words from the lyrics you want to use']"
AddAssignmentPopupVocabularyQuizFirstPopupLocator = "//*[contains(text(),'Create a quiz')]"
MarketplaceCreateALessonCreatedLessonViewEditedLessonViewSendLessonButtonLocator = "//*[text()='Send lesson']"
MarketplaceCreateALessonCreatedLessonViewEditedLessonViewSeeLessonButtonLocator = "//*[text()='See lesson']"
MarketplacePageViewLessonsNumberLocator = "//*[contains(text(),'lessons found')]"
MarketplacePageViewLessonCardLocator = "//*[@id='gallery']/app-lesson-card[1]/div/div[1]"
MarketplacePageViewLessonCardViewUseLessonButtonLocator = "//*[contains(text(),'Use lesson')]"
MarketplacePageViewLessonCardWordsElementLocator = "//*[text()='Words']"
MarketplacePageViewLessonCardMoreFromSameTeacherElementLocator = "//*[text()='More from the same teacher']"
MarketplacePageViewLessonCardWordsLocator = "//*[contains(text(),'Comments')]"
