# Here all the locators of Marketplace page are present

MarketplaceHeadingLocator = "(//*[text()='Marketplace'])[2]"
MarketplaceCreateALessonButtonLocator = "//*[contains(text(),'Create a lesson')]"
MarketplaceCreateALessonTitleFieldLocator = "//*[text()='Title']/../../../input"
MarketplaceCreateALessonDescriptionFieldLocator = "//*[text()='Description']/../../../textarea"
MarketplaceCreateALessonSearchSongFieldLocator = "//*[text()='Search song']/../../../input"
MarketplaceCreateALessonDifficultyFieldLocator = "//*[text()='Difficulty']/../../../mat-select"
MarketplaceCreateALessonDifficultyEasyElementLocator = "//*[text()='Easy']"
MarketplaceCreateALessonDurationFieldLocator = "//*[text()='Duration']/../../../mat-select"
MarketplaceCreateALessonDurationFiveMinutestElementLocator = "//*[contains(text(),'5 minutes')]"
MarketplaceCreateALessonAgeGradeFieldLocator = "//*[text()='Age grade']/../../../mat-select"
MarketplaceCreateALessonAgeGradeSecondGradeElementLocator = "//*[contains(text(),'2nd grade')]"
MarketplaceCreateALessonLearnedWordsFieldLocator = "//*[text()='Learned words']/../../..//input"
MarketplaceCreateALessonMakePublicFieldLocator = "//*[text()='Make public']"
MarketplaceCreateALessonSaveButtonLocator = "//*[contains(text(),'Save')]"
MarketplaceCreateALessonCreatedSuccessMessageLocator = "//*[contains(text(),'Lesson createed successfully.')]"
MarketplaceCreateALessonCreatedLessonHeadingLocator = "//*[@id='main-details']/h1"
MarketplaceCreateALessonCreatedLessonViewEditButtonLocator = "//*[contains(text(),'Edit')]"
MarketplaceCreateALessonCreatedLessonViewUseLessonButtonLocator = "//*[contains(text(),'Use lesson')]"
MarketplaceCreateALessonCreatedLessonViewUseLessonKeepButtonLocator = "//*[text()='Keep']"
MarketplaceCreateALessonCreatedLessonViewUseLessonEditButtonLocator = "//*[text()='Edit']"
MarketplaceCreateALessonCreatedLessonViewUseLessonGroupFieldLocator = "//*[text()='Group']"
MarketplaceCreateALessonCreatedLessonViewUseLessonSendButtonLocator = "//*[text()='Send']"
MarketplaceCreateALessonCreatedLessonViewUseLessonCancelButtonLocator = "//*[contains(text(),'Cancel')]"
MarketplaceCreateALessonCreatedLessonViewUseLessonEditPopupContinueButtonLocator = "//*[text()='Continue']"
MarketplaceCreateALessonCreatedLessonViewUseLessonEditPopupCancelButtonLocator = "//*[contains(text(),'Cancel')]"
MarketplaceCreateALessonCreatedLessonViewLikeButtonLocator = "//*[@id='main-details']/div[1]/button[2]"
MarketplaceCreateALessonCreatedLessonViewDislikeButtonLocator = "//*[@id='main-details']/div[1]/button[3]"
MarketplaceCreateALessonCreatedLessonViewEditLessonHeadingLocator = "//*[contains(text(),'Edit lesson')]"
MarketplaceCreateALessonCreatedLessonViewEditLessonTitleFieldLocator = "//*[text()='Title']/../../../input"
MarketplaceCreateALessonCreatedLessonViewEditLessonDescriptionFieldLocator = "//*[text()='Description']/../../.." \
                                                                             "/textarea"
MarketplaceCreateALessonCreatedLessonViewEditLessonSearchSongFieldLocator = "//*[text()='Search song']/../../../input"
MarketplaceCreateALessonCreatedLessonViewEditLessonDifficultyFieldLocator = "//*[text()='Difficulty']/../../.." \
                                                                            "/mat-select"
MarketplaceCreateALessonCreatedLessonViewEditLessonDifficultyRegularElementFieldLocator = "//*[text()='Regular']"
MarketplaceCreateALessonCreatedLessonViewEditLessonDurationFieldLocator = "//*[text()='Duration']/../../../mat-select"
MarketplaceCreateALessonCreatedLessonViewEditLessonDurationTenMinutesElemenFieldLocator = "//*[contains(text()," \
                                                                                          "'10 minutes')]"
MarketplaceCreateALessonCreatedLessonViewEditLessonAgeGradeFieldLocator = "//*[text()='Age grade']/../../../mat-select"
MarketplaceCreateALessonCreatedLessonViewEditLessonAgeGradeFieldThirdGradeElementLocator = "//*[contains(text()," \
                                                                                           "'3rd grade')]"
MarketplaceCreateALessonCreatedLessonViewEditLessonLearnedWordsFieldLocator = "//*[text()='Learned words']/" \
                                                                              "../../..//input"
MarketplaceCreateALessonCreatedLessonViewEditLessonMakePublicFieldLocator = "//*[text()='Make public']"
MarketplaceCreateALessonCreatedLessonViewEditLessonSaveButtonLocator = "//*[contains(text(),'Save')]"
MarketplaceCreateALessonCreatedLessonViewEditLessonUpdatedSuccessMessageLocator = "//*[contains(text(),'Lesson " \
                                                                                  "updated successfully.')]"
MarketplaceCreateALessonCreatedLessonViewEditedLessonViewDurationLocator = "//*[contains(text(),'Duration')]/" \
                                                                           "../*[contains(text(),'min')]"
MarketplaceCreateALessonCreatedLessonViewEditedLessonViewEditLessonAddAssignmentButtonLocator = "//*[contains(" \
                                                                                                "text(),'Add')]"
AddAssignmentPopupHeadingLocator = "//*[contains(text(),'Select the assignment type from the list below')]"
AddAssignmentPopupGrammarTestLocator = "//*[contains(text(),'Grammar test')]"
AddAssignmentPopupUnseenLocator = "//*[contains(text(),'Unseen')]"
AddAssignmentPopupFillBlanksLocator = "//*[contains(text(),'Fill blanks')]"
AddAssignmentPopupWordPauseLocator = "//*[contains(text(),'Word-pause')]"
AddAssignmentPopupVocabularyQuizLocator = "//*[contains(text(),'Vocabulary quiz')]"
AddAssignmentPopupSpeakingQuizLocator = "//*[contains(text(),'Speaking quiz')]"
AddAssignmentPopupNextButtonLocator = "//*[text()='Next']"
AddAssignmentPopupCreateButtonLocator = "(//*[contains(text(),'Create')])[3]"
AddAssignmentPopupGrammarTestFirstPopupHeadingLocator = "//*[text()='Select the base text for the questions']"
AddAssignmentPopupGrammarTestSecondPopupHeadingLocator = "//*[contains(text(),'Select the questions" \
                                                        " you want to use or create your own')]"
AddAssignmentPopupGrammarTestThirdPopupHeadingLocator = "//*[text()='Review your work']"
AddAssignmentPopupSuccessfulCreation = "//*[contains(text(),'Created successfully')]"
AddAssignmentPopupUnseenFirstPopupHeadingLocator = "//*[text()='Select the base text for the questions']"
AddAssignmentPopupUnseenFirstPopupTextareaLocator = "//*[@id='scroll-wrapper']/form/textarea"
AddAssignmentPopupWordPauseFirstPopupTextareaLocator = "//*[text()='Select words from the lyrics you want to use']"
AddAssignmentPopupVocabularyQuizFirstPopupLocator = "//*[contains(text(),'Create a quiz')]"
MarketplaceCreateALessonCreatedLessonViewEditedLessonViewSendLessonButtonLocator = "//*[text()='Send lesson']"
MarketplaceCreateALessonCreatedLessonViewEditedLessonViewSeeLessonButtonLocator = "//*[text()='See lesson']"
MarketplacePageViewLessonsNumberLocator = "//*[contains(text(),'lessons found')]"
MarketplacePageViewLessonCardLocator = "//*[@id='gallery']/app-lesson-card[1]/div/div[1]"
MarketplacePageViewLessonCardViewUseLessonButtonLocator = "//*[contains(text(),'Use lesson')]"
MarketplacePageViewLessonCardWordsElementLocator = "//*[text()='Words']"
MarketplacePageViewLessonCardMoreFromSameTeacherElementLocator = "//*[text()='More from the same teacher']"
MarketplacePageViewLessonCardWordsLocator = "//*[contains(text(),'Comments')]"
MarketplacePageViewEditedLessonDescriptionFieldLocator = "//*[@id='description']"
MarketplacePageViewEditedLessonGradeFieldLocator = "//*[text()='Age grade']"
MarketplacePageViewEditedLessonDifficultyFieldLocator = "//*[text()='Difficulty']"
MarketplacePageViewEditedLessonDurationFieldLocator = "//*[text()='Duration']"
